FROM phzfi/ubuntu32:bionic-latest

WORKDIR /var/www/html/web
ADD ./scripts/provision.sh ./provision.sh
ADD ./scripts/install-php8.0.sh ./install-php8.0.sh
ADD ./tests/* /opt/

RUN ./provision.sh && ./install-php8.0.sh

ADD ./etc /etc/

CMD ["/usr/sbin/php-fpm8.0", "--fpm-config", "/etc/php/8.0/fpm/php-fpm.conf"]
