FROM phzfi/ubuntu32:bionic-latest

WORKDIR /var/www/html/web
ADD ./scripts/provision.sh ./provision.sh
ADD ./tests/* /opt/

RUN ./provision.sh

ADD ./etc /etc/

CMD ["/usr/sbin/php-fpm7.4", "--fpm-config", "/etc/php/7.4/fpm/php-fpm.conf"]
