#FROM phzfi/ubuntu32:bionic-latest # is actually linux/amd64
FROM phzfi/ubuntu32:bionic-20211118

WORKDIR /var/www/html/web
ADD ./scripts/provision.sh ./provision.sh
ADD ./tests/* /opt/

RUN ./provision.sh 8.0

ADD ./etc /etc/

CMD ["/usr/sbin/php-fpm8.0", "--fpm-config", "/etc/php/8.0/fpm/php-fpm.conf"]
